"use strict";
exports.__esModule = true;
var professional_1 = require("./professional");
var Movie_1 = require("./Movie");
var Imdb_1 = require("./Imdb");
var fs = require('file-system');
var readLineSync = require('readline-sync');
var movie1 = new Movie_1.Movie("Origen", 2010, "USA", "suspense");
movie1.printMovie();
var persona = new professional_1.Professional("Mel Gibson", 65, "Masculine", 78, 1.77, "Green", "Caucasian", "brown", false, "U.S.A.", 2, "Actor");
persona.printAll();
var actor1 = new professional_1.Professional("Amy Adams", 49, "F", 65, 177, "redhead", "blue", "Caucasian", false, "USA", 2, "actor");
var director = new professional_1.Professional("Sam  MEndes", 64, "M", 87, 181, "Brown", "brown", "Caucasian", false, "English", 1, "director");
var writer = new professional_1.Professional("George RR Martin", 76, "M", 123, 190, "Grey", "black", "Caucasian", false, "English", 0, "writer");
movie1.actors = [persona, actor1];
movie1.director = director;
movie1.writer = writer;
movie1.printMovie();
var movie3 = new Movie_1.Movie("1917", 2019, "USA", "war");
movie3.producer = "Amblin PArtners";
movie3.distributor = "Dreamworks";
movie3.isMCU = false;
movie3.language = "English";
movie3.mainCharacterName = "George McCay";
var movie4 = new Movie_1.Movie("The arrival", 2016, "USA", "sci-fi/drama");
movie4.producer = "Lava Bear Films";
movie4.distributor = "PAramount";
movie4.isMCU = false;
movie4.language = "English";
movie3.printMovie();
var biblio = new Imdb_1.Imdb([movie1, movie3, movie4]);
// console.log(JSON.stringify(biblio));
// PROYECTO FIN MODULO 1; AVANZADO; fs.writeFileSync()/fs.readFileSync() y JSON.stringify()/JSON.parse()
// fs.writeFileSync('ImdbBBDD.json', JSON.stringify(biblio));
// let x: Buffer = fs.readFileSync('ImdbBBDD.json');
// console.log(x.toString());
// console.log(JSON.parse(x.toString()));
// console.log(JSON.parse(fs.readFileSync('ImbdBBDD.json')));
var movie5 = new Movie_1.Movie("Capitan America", 2011, "USA", "action");
movie5.language = "English";
movie5.isMCU = true;
movie5.mainCharacterName = "Steve Rogers";
movie5.distributor = "Disney";
movie5.producer = "Marvel Studios";
var movie6 = new Movie_1.Movie("Joker", 2019, "USA", "drama");
movie6.language = "English";
movie6.isMCU = false;
movie6.mainCharacterName = "Arthur Fleck";
movie6.distributor = "Warner Bros. Pictures";
movie6.producer = "DC Films";
var films = new Imdb_1.Imdb([movie5, movie6]);
films.escribirEnFicheroJSON("ficheroPrueba");
var nofilm = new Movie_1.Movie("", 0, "", "");
var prueba;
prueba = films.obtenerInstanciaIMDB("ficheroPrueba");
console.log(prueba);
var titlea = readLineSync.question("Introduzca titulo de la pelicula: ");
var releaseYeara = readLineSync.question("Intrudozca anyo de estreno de la pelicula: ");
var nationalitya = readLineSync.question("Intrudozca nacionalidad de la pelicula: ");
var genrea = readLineSync.question("Introduzca genero de la pelicula: ");
var producera = readLineSync.question("Introduzca productora de la pelicula: ");
var distributora = readLineSync.question("Introduzca distribuidora de la pelicula: ");
var isMCUa = readLineSync.question("Intrudozca si esta dentro del MCU de la pelicula(true/false): ");
var mainCharacterNamea = readLineSync.question("Intruduzca nombre del personaje principal de la pelicula: ");
var laguagea = readLineSync.question("Intruduzca lenguaje original de la pelicula: ");
var moviea = new Movie_1.Movie(titlea, releaseYeara, nationalitya, genrea);
moviea.distributor = distributora;
moviea.producer = producera;
moviea.isMCU = isMCUa;
moviea.mainCharacterName = mainCharacterNamea;
moviea.language = laguagea;
prueba.push(moviea);
console.log(prueba);
